import test from 'node:test';
import assert from 'node:assert/strict';
import { aiImageProviderRegistry } from '../../server/services/media/aiImageProviderRegistry.js';
import { buildAiImageIntent } from '../../server/services/media/aiImageIntentBuilder.js';
import { type GeneratedMediaProvider, type GeneratedMediaRequest, type GeneratedMediaResult } from '../../server/services/media/aiImageProviderRegistry.types.js';
import { ComfyUiProvider } from '../../server/services/media/providers/comfyui.js';
import { MediaProviderError } from '../../server/services/media/mediaProvider.js';

class MockAiProvider implements GeneratedMediaProvider {
  id = 'mock-ai';
  displayName = 'Mock AI';
  capabilities: ('image-generation')[] = ['image-generation'];
  costMode: 'paid' | 'local-free' | 'remote-free' | 'free-tier' = 'local-free';
  requiresApiKey = false;
  requiresBilling = false;
  isLocal = true;
  enabledByDefault = true;
  
  isConfigured() { return true; }

  async generate(request: GeneratedMediaRequest): Promise<GeneratedMediaResult> {
    return {
      candidateId: 'mock-gen-123',
      requestId: request.requestId,
      provider: 'dall-e' as const,
      providerAssetId: 'mock-asset',
      sourceType: 'generated' as const,
      previewUrl: 'https://example.com/mock.jpg',
      width: 1024,
      height: 1024,
      aspectRatio: request.aspectRatio,
      licenseLabel: 'Generated by Mock',
      attributionRequired: false,
      retrievedAt: new Date().toISOString(),
      confidence: 0.95,
      binary: Buffer.from('fake-image-data')
    };
  }
}

class MockPaidProvider extends MockAiProvider {
  id = 'mock-paid';
  displayName = 'Mock Paid';
  costMode = 'paid' as const;
  requiresApiKey = true;
  requiresBilling = true;
  isLocal = false;
}

aiImageProviderRegistry.register(new MockAiProvider());
aiImageProviderRegistry.register(new MockPaidProvider());

test('AI Image Intent Builder', async (t) => {
  await t.test('strips PII and creates generic prompt', () => {
    const request: GeneratedMediaRequest = {
      requestId: 'req-1',
      section: 'hero',
      niche: 'Barbearia',
      purpose: 'Uma barbearia moderna',
      designFamily: 'bold',
      aspectRatio: '16:9'
    };
    const intent = buildAiImageIntent(request);
    
    assert.ok(intent.includes('Bold, vibrant photography'), 'Applies design family style');
    assert.ok(intent.includes('Focus: Barbearia'), 'Includes niche context');
    assert.ok(intent.includes('A stunning hero image depicting Uma barbearia moderna.'), 'Includes section & purpose mapping');
    assert.ok(intent.includes('CRITICAL RULES: No text, no words'), 'Includes safety rules');
  });
});

test('AI Image Provider Registry', async (t) => {
  await t.test('resolves registered provider and generates', async () => {
    const result = await aiImageProviderRegistry.generate({
      requestId: 'req-test',
      section: 'hero',
      niche: 'Teste',
      purpose: 'Teste purpose',
      aspectRatio: '1:1',
      provider: 'mock-ai'
    });

    assert.equal(result.candidateId, 'mock-gen-123');
    assert.equal(result.previewUrl, 'https://example.com/mock.jpg');
    assert.equal(result.aspectRatio, '1:1');
    assert.ok(Buffer.isBuffer(result.binary));
  });

  await t.test('blocks paid providers under ZERO_COST_ONLY', async () => {
    process.env.AI_IMAGE_ZERO_COST_ONLY = 'true';
    
    try {
      await aiImageProviderRegistry.generate({
        requestId: 'req-test-paid',
        section: 'hero',
        niche: 'Teste',
        purpose: 'Teste purpose',
        aspectRatio: '1:1',
        provider: 'mock-paid'
      });
      assert.fail('Should have thrown an error for paid provider');
    } catch (err: any) {
      assert.equal(err.code, 'MEDIA_PROVIDER_NOT_CONFIGURED');
      assert.ok(err.message.includes('not eligible under current cost policy'));
    }
  });

  await t.test('auto router routes to local-free and skips paid', async () => {
    process.env.AI_IMAGE_ZERO_COST_ONLY = 'true';
    
    // Call generate without specifying a provider
    const result = await aiImageProviderRegistry.generate({
      requestId: 'req-auto',
      section: 'hero',
      niche: 'Teste',
      purpose: 'Teste purpose',
      aspectRatio: '1:1'
    });

    // Should resolve via mock-ai since mock-paid is skipped
    assert.equal(result.candidateId, 'mock-gen-123');
  });

  await t.test('zero-cost regression: paid provider call count is 0 when local fails', async () => {
    process.env.AI_IMAGE_ZERO_COST_ONLY = 'true';
    
    let paidCallCount = 0;
    class MockPaidProviderCounter extends MockAiProvider {
      id = 'mock-paid-counted';
      costMode = 'paid' as const;
      async generate(request: GeneratedMediaRequest) {
        paidCallCount++;
        return super.generate(request);
      }
    }
    
    class MockFailingLocalProvider extends MockAiProvider {
      id = 'mock-local-failing';
      costMode = 'local-free' as const;
      async generate(request: GeneratedMediaRequest): Promise<GeneratedMediaResult> {
        throw new MediaProviderError('MEDIA_PROVIDER_UNAVAILABLE', 'Failing local provider');
      }
    }
    
    aiImageProviderRegistry.register(new MockPaidProviderCounter());
    aiImageProviderRegistry.register(new MockFailingLocalProvider());
    
    try {
      // Force it to use the new auto router logic with just these
      const originalProviders = [...(aiImageProviderRegistry as any).providers.values()];
      (aiImageProviderRegistry as any).providers.clear();
      aiImageProviderRegistry.register(new MockPaidProviderCounter());
      aiImageProviderRegistry.register(new MockFailingLocalProvider());
      
      await aiImageProviderRegistry.generate({
        requestId: 'req-auto',
        section: 'hero',
        niche: 'Teste',
        purpose: 'Teste purpose',
        aspectRatio: '1:1'
      });
      assert.fail('Should have exhausted providers');
    } catch (err: any) {
      assert.equal(paidCallCount, 0, 'Paid providers must never be called under zero-cost mode, even as fallbacks.');
      assert.equal(err.code, 'MEDIA_PROVIDER_UNAVAILABLE');
    }
  });
});

test('ComfyUI Real Generation Flow', async (t) => {
  const originalFetch = global.fetch;

  t.afterEach(() => {
    global.fetch = originalFetch;
    process.env.COMFYUI_BASE_URL = '';
  });

  await t.test('Integration: full generation (pending -> output -> view URL)', async () => {
    process.env.COMFYUI_BASE_URL = 'http://comfyui.mock';
    let historyPollCount = 0;

    global.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
      const url = input.toString();
      if (url.endsWith('/system_stats')) {
        return new Response(JSON.stringify({ system: { os: 'mock' } }), { status: 200 });
      }
      if (url.endsWith('/prompt') && init?.method === 'POST') {
        return new Response(JSON.stringify({ prompt_id: 'prompt-123' }), { status: 200 });
      }
      if (url.includes('/history/prompt-123')) {
        historyPollCount++;
        if (historyPollCount < 2) {
          // First poll: pending
          return new Response(JSON.stringify({}), { status: 200 });
        }
        // Second poll: finished
        return new Response(JSON.stringify({
          'prompt-123': {
            outputs: {
              '9': {
                images: [{ filename: 'test.png', subfolder: '', type: 'output' }]
              }
            }
          }
        }), { status: 200 });
      }
      throw new Error(`Unexpected fetch to ${url}`);
    };

    const provider = new ComfyUiProvider();
    const result = await provider.generate({
      requestId: 'req',
      section: 'hero',
      niche: 'Barbearia',
      purpose: 'Barbearia hero',
      aspectRatio: '1:1'
    });

    assert.ok(result.candidateId.startsWith('comfyui_'));
    assert.equal(result.previewUrl, 'http://comfyui.mock/view?filename=test.png&type=output');
    assert.equal(historyPollCount, 2);
  });

  await t.test('Integration: timeout control (prompt never finishes)', async () => {
    process.env.COMFYUI_BASE_URL = 'http://comfyui.mock';

    global.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
      const url = input.toString();
      if (url.endsWith('/system_stats')) return new Response('{}', { status: 200 });
      if (url.endsWith('/prompt')) return new Response(JSON.stringify({ prompt_id: 'prompt-456' }), { status: 200 });
      if (url.includes('/history/prompt-456')) {
        // always pending
        return new Response(JSON.stringify({}), { status: 200 });
      }
      throw new Error(`Unexpected fetch to ${url}`);
    };

    const provider = new ComfyUiProvider();
    
    // We mock setTimeout to skip the 1-second delay for testing timeout quickly
    const originalSetTimeout = global.setTimeout;
    (global as any).setTimeout = ((cb: any, ms: number) => {
      // Execute the callback immediately to skip waiting
      return originalSetTimeout(cb, 0);
    }) as any;

    try {
      await provider.generate({
        requestId: 'req',
        section: 'hero',
        niche: 'Barbearia',
        purpose: 'Barbearia hero',
        aspectRatio: '1:1'
      });
      assert.fail('Should have thrown timeout error');
    } catch (e: any) {
      assert.equal(e.code, 'MEDIA_PROVIDER_TIMEOUT');
      assert.ok(e.message.includes('timed out'));
    } finally {
      global.setTimeout = originalSetTimeout;
    }
  });

  await t.test('Integration: execution error (ComfyUI history empty output)', async () => {
    process.env.COMFYUI_BASE_URL = 'http://comfyui.mock';

    global.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
      const url = input.toString();
      if (url.endsWith('/system_stats')) return new Response('{}', { status: 200 });
      if (url.endsWith('/prompt')) return new Response(JSON.stringify({ prompt_id: 'prompt-err' }), { status: 200 });
      if (url.includes('/history/prompt-err')) {
        return new Response(JSON.stringify({
          'prompt-err': {
            outputs: {} // Empty output means it finished but produced no images
          }
        }), { status: 200 });
      }
      throw new Error(`Unexpected fetch to ${url}`);
    };

    const provider = new ComfyUiProvider();
    try {
      await provider.generate({
        requestId: 'req',
        section: 'hero',
        niche: 'Barbearia',
        purpose: 'Barbearia hero',
        aspectRatio: '1:1'
      });
      assert.fail('Should have thrown execution error');
    } catch (e: any) {
      assert.equal(e.code, 'MEDIA_PROVIDER_INVALID_RESPONSE');
      assert.ok(e.message.includes('produced no outputs'));
    }
  });
});
